### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by jyschwrtz** [jyschwrtz/Pied-Piper#1]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by s-pangburn** [comment]
Okay, here's my feedback for you!

- [x] Change tab title to Pied Piper
- [x] Move login/signup form to main page
- [x] Logout button should have more padding
- [x] There shouldn't be a "Demo Signup" - change it to always be "Demo Login"
  + it's kind of awkward how it doesn't fill the "email" field and signs you in anyway. I'm assuming since it's the demo_user it really is still just logging you in instead of creating a new user? If that's the case, please have it switch to the login form before it simulates typing the credentials.
- [x] Errors should clear when switching between forms

**Comment by s-pangburn** [comment]
- [x] "Try it out without signing up?" <- a little awkward and makes the form look cluttered, probably don't have this at all.
- [x] Ideally demo login should be on both forms. This seems like a minor point, but the less times a recruiter has to click to get into your app, the better it is for you. Try your best to get that working, but if you start to feel you don't have enough time, feel free to let me know and I can just let you move on.
- [x] Errors should be red (I realize this seems less readable, but I tested it in the chrome console and I believe the result is acceptable and communicates the nature of the error messages better)

Great work so far!

**Comment by s-pangburn** [comment]
- [x] Make errors yellow
- [x] Redirect to login from random urls

Awesome job Jay! It's looking really good!
