### ISSUE TITLE
PA Review: Song/Playlist CRUD

### ISSUE THREAD

**Issue by jyschwrtz** [jyschwrtz/Pied-Piper#6]
- [x] Songs and playlist backend tables & models
- [x] Songs and playlist API controllers, routes, and correct jbuilders
- [x] Utils, Actions, & Reducers
- [x] Components & Containers
- [x] Users can create, view (index and show), and edit playlists
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

Do not give frontend access to creating and destroying songs.  CRUD only on the playlists for users.

**Comment by s-pangburn** [comment]
- [x] When you press the Play button next to a song, the song is queued up but does not immediately start playing. You actually have to click the play button again to get the song to start. Ideally, try to fix this. Less patient recruiters may simply assume the song playing doesn't work, which obviously isn't true.
   + Upon further testing, it looks like this only happens when you click the play button next to the song directly. If you click the div it starts normally. I think what is happening is that the song is playing then immediately pausing (registering two clicks at a time?) But it's impossible to tell without looking at the code directly. In any case, it only happens when you click the play button that appears right next to the song.
- [x] When you finish adding a song to the playlist, the "Add to Playlist - Remove from this Playlist" dropdown is still there.
- [x] Removing a song from a playlist starts the song in the player.
- [x] In the playlist view, the play button on the album art should `cursor: pointer` on hover
- [x] Not sure how to edit a playlist
- [x] User-created playlists without album art still display the album art play button if you hover over the title.

**Comment by s-pangburn** [comment]
👍
